### ISSUE TITLE
gorule-0000013 taxon constraints should be implemented as FILTERS (hard rule)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#763] opened 2018-08-14 14:43 UTC
Decision from QCQA group Aug 14 2018.

**Comment by ValWood** [comment] 2019-03-12 16:35
for example these, should just not get through...

![filter](https://user-images.githubusercontent.com/7359272/54218029-a8fe9680-44e4-11e9-8e86-414d2125b669.jpg)

@pgaudet  I won't report these because I presume there are a sytems in place to  alert PAINT curators to taxon violations?

**Comment by dougli1sqrd** [comment] 2019-11-26 20:38
Duplicate of https://github.com/geneontology/go-site/issues/882

**Closed by dougli1sqrd** 2019-11-26 20:38 UTC
Labels: annotation rule
