### ISSUE TITLE
Annotation files on GO-website - are they pointing to the correct releases? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#703] opened 2018-07-13 15:07 UTC
Links on this page: http://geneontology.org/page/download-go-annotations
Go to, for eg: http://geneontology.org/gene-associations/goa_human.gaf.gz

Shouldn't they go to 
http://current.geneontology.org/annotations/index.html
(for example: http://current.geneontology.org/annotations/goa_human.gaf.gz) ? 

Thanks, 

Pascale and @ukemi 

@kltm @cmungall

**Comment by kltm** [comment] 2018-07-13 17:08
Dupe of #491 (and #492 )

**Closed by kltm** 2018-07-13 17:08 UTC
Labels: duplicate
