### ISSUE TITLE
Create a new xref for "annotation of amyloid-beta binding proteins" project

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#299] opened 2017-01-12 19:48 UTC
From @BarbaraCzub
```
...a request to generate a DefX_Ref for our new project, i.e. annotation of 
amyloid-beta binding proteins, funded by Alzheimer's Research UK. Could 
you please create the DefX_Ref GOC:ARUK for this project?
```
@cmungall are we using just the "new" method at this point for everything, or do we still need to update the old CGI data as well?

**Comment by cmungall** [comment] 2017-01-13 00:54
just the new

**Comment by kltm** [comment] 2017-01-13 01:08
Talked with @cmungall a little bit about this. At some point we'll probably want to merge and/or sort out the slightly overlapping domains of users.yaml, groups.yaml, and the new GO_REFs files in the metadata. However, for the time being, we'll just do it the "old" way, by adding it to the users.yaml file (which has what URI reference again?).

**Comment by kltm** [comment] 2017-01-13 01:12
@BarbaraCzub I've added something with the last commit, although you may want to change the `organization`. See "GOC:aruk".

**Comment by BarbaraCzub** [comment] 2017-01-13 11:18
Thanks.

**Comment by BarbaraCzub** [comment] 2017-01-13 11:47
@kltm re: organisation, do you mean that this should be ARUK-UCL ?

If we compare for instance to the Parkinson's project, the xref in TermGenie comes up as "GOC:PARL", but the GitHub label is "PARL-UCL". 

So I'm assuming you are suggesting that for Alzheimer's it should correspondingly be xref "GOC:ARUK" and GitHub label "ARUK-UCL". Could you also please add this "ARUK-UCL" label to be available on GitHub?


@RLovering

**Comment by BarbaraCzub** [comment] 2017-01-16 11:27
Hi @kltm,

Should we expect the "ARUK-UCL" label to be available yet? (it is not).

And also, could the "ARUK" in "GOC:ARUK" be spelt with capital letters? (Currently it gets displayed as "GOC:aruk" in TermGenie. "ARUK" is an acronym for Alzheimer's Research UK and we would appreciate it a lot, if this was reflected in the xref.

Thanks!

@RLovering

**Comment by kltm** [comment] 2017-01-16 14:02
@BarbaraCzub Would you know if these identifiers have been committed out to any files yet?
@cmungall I'm sorry to pass this on to you, but I'm not sure of the procedure here once ids have leaked out. The /vast/ majority of identifiers in users.yaml and lower, so I figured that was how it rolled.

**Comment by BarbaraCzub** [comment] 2017-01-16 15:36
@kltm I have not used any of these identifiers to request any new terms yet, so nothing should have been committed to any files yet.

@cmungall 
@RLovering

**Comment by cmungall** [comment] 2017-01-16 21:22
Sorry, I'm missing precisely what the problem is.

We have GOC:aruk in users.yaml:

https://github.com/geneontology/go-site/blob/fc68e14d9d3f70fb5a09f663a3346c980f11e142/metadata/users.yaml#L601

You can go ahead and use this in definition xrefs in the ontology. I tested TermGenie, and GOC:aruk is available in the dropdown.

@tonysawfordebi added ARUK-UCL to db-xrefs.yaml 8 days ago:

https://github.com/geneontology/go-site/blob/68a91d84b934b0634a560fcca690d54f91484fa0/metadata/db-xrefs.yaml#L87-L93

I don't think this is intended, ARUK-UCL is not a database does not mint IDs. I suggest we remove this

**Comment by RLovering** [comment] 2017-01-17 08:32
Hi All

sorry this is my fault, I hadn't appreciated that I could add a new github label to the ontology github section. I thought someone else had to do this. So it is now possible for Barbara to submit a request for a new GO term with the github label ARUK-UCL. I will suggest that she includes the dbxref: GOC:ARUK for now in these request, to make sure that the editors include this DBXref any new terms created following Barbara's requests. It would be nice if in termgenie the option for the dbxref was GOC:ARUK rather than GOC:aruk, however it looks like Barbara can just write this in in capitals rather than using the dropdown selection. Therefore I think this issue can be closed.

Barbara, please send a ARUK logo to Tony so that any terms created will have this LOGO included on the QuickGO record, and mention that these will have the dbxref: GOC:ARUK or GOC:aruk.

Many thanks and apologies

Ruth

**Closed** 2017-01-18 02:10 UTC
Labels: enhancement, metadata
