### ISSUE TITLE
Discuss the right approach to dealing with GOA tRNA increase

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1185] opened 2019-09-26 23:09 UTC
For ongoing discussion, as we are putting in measures to bypass the immediate problems #1168 .

From my memory, due to the spike in IEA tRNA annotations available in GOA , it was decided to reach out to them and see if we could get two versions, IEA and non-IEA, the latter of which we now consume.

There is a question as to whether this is a good long-term solution and that perhaps this should be fixed in a more systematic way upstream.

Tagging @pgaudet @cmungall

**Comment by pgaudet** [comment] 2019-09-30 13:45
This is the correct solution until RNA central provides the equivalent of a Reference Proteome version of RNAs- right now they include ALL sequenced RNAs, so probably many redundant sequences. 

What is the action here ? 

Thanks, Pascale

**Comment by kltm** [comment] 2019-09-30 20:23
This is a placeholder for the moment for you (@pgaudet ) to start a conversation with @cmungall about a long-term solution.

**Comment by pgaudet** [comment] 2019-09-30 21:49
@thomaspd was going to ask colleagues at the EBI.

**Comment by pgaudet** [comment] 2024-07-15 18:11
Duplicate of https://github.com/geneontology/go-site/issues/1168

Now that we load the 'GOA-plus' files this is not an issue anymore.

**Closed by pgaudet** 2024-07-15 18:11 UTC
Labels: question
