### ISSUE TITLE
Changes to annotation files submitted by GOA

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#185] opened 2016-04-26 07:06 UTC
We (GOA) currently submit the following files to the GOC SVN repository:

GO-SVN/trunk/gene-associations/submission/

    gene_association.goa_<species>.gz - annotations to proteins that are part of the UniProt *complete* proteome, *plus* isoforms, complexes, and RNAs
    gene_association.goa_ref_<species>.gz - annotations to canonical accessions from the UniProt gene-centric reference proteome (GCRP)

    gene_association.goa_uniprot.gz
    gene_association.goa_pdb.gz

GO-SVN/trunk/gpad-gpi/submission/

    gp_association.goa_ref_<species>.gz - annotations to canonical accessions from the UniProt gene-centric reference proteome (GCRP)
    gp_information.goa_ref_<species>.gz - metadata only for canonical accession from the GCRP

where <species> is one of: human, chicken, cow, dog, pig

At the recent GOC meeting in Geneva, we announced our intention to revise the set of files that we publish as part of our four-weekly release cycle in order to eliminate confusion that has arisen in the past about what the various files contain.

As of the GOA release that is scheduled for the week of 9th May, we intend to change the set of files that we publish and submit to the GOC repository to the following:

GO-SVN/trunk/gene-associations/submission/

    goa_<species>.gaf.gz - annotations to canonical accessions from the UniProt GCRP
    goa_<species>_isoform.gaf.gz - annotations to isoforms from the UniProt GCRP
    goa_<species>_complex.gaf.gz - annotations to complexes
    goa_<species>_rna.gaf.gz - annotations to RNAs

    goa_uniprot_all.gaf.gz - renamed gene_association.goa_uniprot.gz; identical content
    goa_pdb.gaf.gz - renamed gene_association.goa_pdb.gz; identical content

GO-SVN/trunk/gpad-gpi/submission/

    goa_<species>.gpa.gz - annotations to canonical accessions from the UniProt GCRP
    goa_<species>_isoform.gpa.gz - annotations to isoforms from the UniProt GCRP
    goa_<species>_complex.gpa.gz - annotations to complexes
    goa_<species>_rna.gpa.gz - annotations to RNAs
    goa_uniprot_all.gpa.gz - renamed gp_association.goa_uniprot.gz; identical content

    goa_<species>.gpi.gz - metadata for canonical accessions from the UniProt GCRP
    goa_<species>_isoform.gpi.gz - metadata for isoforms from the UniProt GCRP
    goa_<species>_complex.gpi.gz - metadata for complexes
    goa_<species>_rna.gpi.gz - metadata for RNAs

Again, <species> is one of: human, chicken, cow, dog, pig

As you can see, as well as rationalising the contents of the files that we produce, we are also proposing changing their names; we're doing this for two reasons:

1) it emphasises that the annotation sets in these new files are not the same as those in the current files; the goa_<species> sets will now contain annotations only to proteins that are canonical accessions from the UniProt GCRP for the species, whereas in the current files they contain annotations to canonical accessions *and* isoforms from the UniProt *complete* proteome for the species, plus RNAs and complexes.
2) it makes more sense for the format of the contents to be indicated by the file suffix rather than prefix

Comments / suggestions / objections?

**Comment by cmungall** [comment] 2016-04-27 00:34
Link to trello: https://trello.com/c/holv0gEG/151-reference-proteome-should-be-default

**Comment by cmungall** [comment] 2016-04-27 00:37
+1 to the change, *provided* we have addressed issues here: https://github.com/geneontology/go-annotation/issues/1113 -- specifically, do we lose any annotations that are assigned to a non-GCRP when they should be assigned to a GCRP?

May 9 is only a two week lag. It may take some time for people to change their pipelines.

**Comment by cmungall** [comment] 2016-04-27 00:46
Checklist:

 - [ ] send advance notification
 - [ ] add JSON metadata files (these drive the main website)
 - [ ] modify go/software/utilities/filter-gene-association.pl
 - [ ] sync changes with legacy CVS repo

**Comment by ValWood** [comment] 2016-04-27 06:05
+10 !

**Comment by ValWood** [comment] 2016-04-27 06:13
One thought.

a) I'm assuming  that the "isoform file" will  be the contain only the automated annotations on Trembl entries? In which sase it isn't only isoforms, but also any truncated, alternative entry which isn't integrated into the UniProt record (UniProt may want to correct me here).

b) Sometimes a GO annotator will make an experimental annotation to an isoform using the canonical entry using column 17 	(UniProtKB:P12345-2)...I'm guessing/hoping these will still be in the main file (because they will have the canonical ID in column 2).

So if the above is correct, the file naming/contents description might be confusing if people really are interested in isoform annotations....However, its probably only a file description issue.....the data spilt  described is completely necessary

**Comment by cmungall** [comment] 2016-04-27 18:40
point a, isoforms: just realized I am not clear on what this is. "isoforms from the UniProt GCRP" sounds like a bit of a contradictory term, since unless I'm not mistaken the GCRP by design avoids either true isoforms or alternate records.

Perhaps this is just the current goa_$species, minus GCRP, RNA and complexes. In which case I would go with a name like "_altids" rather than "_isoforms" (sorry, can't think of a better suggestion now). We should also document a use case for this file. I agree "_isoforms" is potentially confusing if these are alternate records rather than true isoforms.

b - my understanding is the same as yours. And I agree it's confusing to have the altid file called "isoforms" as it would lead people to believe they would not get isoforms from the default file.

**Comment by vanaukenk** [comment] 2016-04-27 20:00
With regard to Tony's point 2:

2) it makes more sense for the format of the contents to be indicated by the file suffix rather than prefix

I completely agree, and is the plan that this practice will be adopted consortium-wide?

**Comment by tonysawfordebi** [comment] 2016-04-28 09:54
In the light of comments about timing, we've decided to postpone rolling out these changes until the GOA release scheduled for the week of 6th June; this gives people an extra four weeks to make any necessary preparations.

**Comment by tonysawfordebi** [comment] 2016-05-04 10:51
I've created some sample files for human and mouse; you can find them at ftp://ftp.ebi.ac.uk/pub/contrib/goa/new-files/

**Comment by cmungall** [comment] 2016-06-08 22:00
Continued in #190

**Closed** 2016-06-08 22:00 UTC
