### ISSUE TITLE
Reports gorule-0000009 (Matrix/co-annotation) should be split by species and included in reports

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1247] opened 2019-11-26 13:11 UTC
Hello, 

Reported by @ValWood : 

Right now gorule-0000009 (Matrix/co-annotation) is only reported in 
http://snapshot.geneontology.org/reports/shared-annotation-check.html

Unfortunately this isn't so useful  because there is no easy way to  know if a rule violation includes your species of interest without clicking on the link- and there are 107 rules! On the plus side the number of violations is generally very, very low.

Thanks, Pascale

**Comment by kltm** [comment] 2019-11-26 19:17
Dupe of: https://github.com/geneontology/shared-annotation-check/issues/2

**Closed by kltm** 2019-11-26 19:17 UTC
Labels: annotation rule
