### ISSUE TITLE
KEGG2GO mapping file appears truncated on current and snapshot

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1139] opened 2019-07-07 23:58 UTC
A user reported to the helpdesk that the KEGG2GO mapping file available for download appears to be truncated:

http://current.geneontology.org/ontology/external2go/kegg2go

The current file, in its entirety, is:

```
! Generated on 2019-07-01T18:49Z from the ontology 'go' with data version: 'releases/2019-07-01'
!
KEGG:ko00730 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:ko00900 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:ko01100 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:ko01110 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01060 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01062 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01066 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01070 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
```

Noting similarity to issues with #1031 .

**Comment by kltm** [comment] 2019-07-07 23:59
@balhoff @goodb As the actors on on #1031 , would it be possible for one of you to take a look at this?

**Comment by kltm** [comment] 2019-07-08 00:01
Considering that this is the second time that this has happened, perhaps there should be an overall audit of the current external2go files as provided.

**Comment by goodb** [comment] 2019-07-08 16:42
@kltm I don't think anything we did with the Reactome mapping would apply to KEGG.  As far as I know, Reactome is the only external database to provide the mapping file format expected by the ontology makefile.  

Based on the comment in the Makefile (see below) and what happened last time with Reactome, I would guess there may be a mismatch between the manually edited kegg xrefs in the go-edit.obo file and the expected namespace in the db-xrefs.yaml file https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml 

The relevant part of the Makefile:
# ----------------------------------------
# MAPPINGS
# ----------------------------------------
EXTERNAL2GO_DBS = EC KEGG MetaCyc Reactome RESID UM-BBD_enzymeID UM-BBD_pathwayID Wikipedia RHEA

# See : https://github.com/geneontology/go-site/issues/688
# Manually add all ID spaces here; only do this for xrefs that are managed within the obo file.
# NOTE: rfam2go location is temporary until FTP up, see: https://github.com/geneontology/go-ontology/issues/17153
.PHONY: generate-mappings
generate-mappings: go-basic.obo
	$(OWLTOOLS) $< --external-mappings-files -o external2go --label-prefix GO: --externals $(EXTERNAL2GO_DBS)
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/interpro2go -O external2go/interpro2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/pfam2go -O external2go/pfam2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/pirsf2go -O external2go/pirsf2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/prints2go -O external2go/prints2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/prodom2go -O external2go/prodom2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/prosite2go -O external2go/prosite2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/smart2go -O external2go/smart2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/uniprotkb_kw2go -O external2go/uniprotkb_kw2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/uniprotkb_sl2go -O external2go/uniprotkb_sl2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/unirule2go -O external2go/unirule2go
	wget ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/hamap2go -O external2go/hamap2go
	wget http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/external2go/rfam2go -O external2go/rfam2go

**Comment by ukemi** [comment] 2019-07-08 17:48
@pgaudet, didn't you recently edit the KEGG xrefs?

https://github.com/geneontology/go-ontology/pull/17492

**Comment by pgaudet** [comment] 2019-07-09 09:02
Yes - I all the KEGG-reactions: 

https://github.com/geneontology/go-ontology/commit/4eacb6cea403c2c4cc264d215e8fcd4260cd75d7

**Comment by pgaudet** [comment] 2019-07-09 09:09
This was done because the links to KEGG were not working: 
https://github.com/geneontology/amigo/issues/568

**Comment by kltm** [comment] 2019-07-09 16:08
@pgaudet From @goodb 's comment above, the db-xrefs.yaml and ontology information needs to be aligned for us to get the expected output with the current setup.

**Comment by goodb** [comment] 2019-07-09 16:12
@kltm it looks like the db-xrefs.yaml is okay.  I'm guessing here as this is an OWLTools thing and I haven't really used it but I wager that if this line in the build file:

EXTERNAL2GO_DBS = EC KEGG MetaCyc Reactome RESID UM-BBD_enzymeID UM-BBD_pathwayID Wikipedia RHEA

was changed to:
EXTERNAL2GO_DBS = EC KEGG KEGG_REACTION MetaCyc Reactome RESID UM-BBD_enzymeID UM-BBD_pathwayID Wikipedia RHEA

(with addition of the KEGG_REACTION namespace)
things might just work.

**Comment by kltm** [comment] 2019-07-09 16:20
For @goodb and/or @cmungall :
https://github.com/geneontology/go-ontology/pull/17606

**Comment by kltm** [comment] 2019-07-09 17:22
Now testing:
```
docker run -it obolibrary/odkfull:v1.1.7 /bin/bash
git clone https://github.com/geneontology/go-ontology.git
cd go-ontology
git checkout issue-go-site-1139-kegg-mapping
cd src/ontology
OBO=http://purl.obolibrary.org/obo RELEASEDATE=2019-07-09 make all
```

**Comment by kltm** [comment] 2019-07-09 17:39
@goodb and @cmungall 
Okay, tested. kegg2go is still "truncated" and we have a new file kegg_reaction2go:
```
root@38c65cb507ce:/tools/go-ontology/src/ontology/external2go# wc kegg_reaction2go 
  1805  12810 145085 kegg_reaction2go
```
I'm not sure if this actually constitutes the fix we're looking for.

**Comment by goodb** [comment] 2019-07-09 17:40
@kltm what is in the kegg_reaction2go file ?  It makes sense that we would end up with a new file.

**Comment by kltm** [comment] 2019-07-09 17:46
@goodb 
```
[...]
KEGG_REACTION:R01563 > GO:N-carbamoylsarcosine amidase activity ; GO:0050127
KEGG_REACTION:R01564 > GO:dimethylglycine oxidase activity ; GO:0047866
KEGG_REACTION:R01565 > GO:dimethylglycine dehydrogenase activity ; GO:0047865
KEGG_REACTION:R01566 > GO:creatinase activity ; GO:0016980
KEGG_REACTION:R01573 > GO:D-arabinokinase activity ; GO:0047814
KEGG_REACTION:R01576 > GO:3-deoxy-D-manno-octulosonate aldolase activity ; GO:00
[...]
```

**Comment by kltm** [comment] 2019-07-09 17:47
Is the idea then to basically drop the kegg2go file?

**Comment by goodb** [comment] 2019-07-09 17:50
@kltm That file seems good to me.  

I think what they want are (at least) two different kinds of mappings.  e.g. KEGG, KEGG_REACTION, KEGG_PATHWAY etc.  - that is what I see in the yaml file.  We could concatenate them all into one uber KEGG file I guess, but seems reasonable enough to simply provide the collection.  

We should check that all of the plain 'KEGG' xrefs appear in the kegg2go file.

**Comment by kltm** [comment] 2019-07-09 17:55
The current complete kegg2go (in my test) is:
```
root@38c65cb507ce:/tools/go-ontology/src/ontology/external2go# cat kegg2go 
! Generated on 2019-07-09T17:34Z from the ontology 'go' with data version: 'releases/2019-07-09'
!
KEGG:ko00730 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:ko00900 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:ko01100 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:ko01110 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01060 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01062 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01066 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
KEGG:map01070 > GO:1-deoxy-D-xylulose 5-phosphate metabolic process ; GO:0052863
```
which doesn't really seem worthwhile.

**Comment by goodb** [comment] 2019-07-09 18:08
@kltm it looks like it really is a global conversion to KEGG_REACTION.  I don't see any other xrefs to KEGG: apart from those you list (notably all for GO:0052863 ) which seem like possible bugs.  

@pgaudet I do see some other references to KEGG: in the synonym slot.  e.g. for id: GO:0004506 
synonym: "squalene,NADPH:oxygen oxidoreductase (2,3-epoxidizing) activity" EXACT [KEGG:R02874]
which also has:
xref: KEGG_REACTION:R02874 

I suspect these synonym matches might either need to be converted to the new pattern (though that should not affect the current problem) or might better simply be deleted.  

My conclusion here would be that the build is working properly and that the user that noticed this and started the thread should be alerted to the presence of the new kegg_reaction2go which will contain the mappings that they need.

**Comment by kltm** [comment] 2019-07-09 18:16
@goodb No matter, having the data pop out somewhere is an improvement, so on your okay (or PR review) I'll merge that in and we can move forward from there.

**Comment by goodb** [comment] 2019-07-09 18:25
Seems okay for me.

**Comment by pgaudet** [comment] 2019-08-13 17:10
The KEGG2GO file is still truncated; can someone look into it ? 
http://snapshot.geneontology.org/ontology/external2go/kegg2go

Thanks, Pascale

**Comment by ukemi** [comment] 2019-08-13 17:13
But there is another Kegg_reaction file. This one has a lot more lines. Is this a result of the editing of the xrefs and were a few missed?

**Comment by ukemi** [comment] 2019-08-13 17:13
http://snapshot.geneontology.org/ontology/external2go/kegg_reaction2go

**Comment by pgaudet** [comment] 2019-08-14 09:33
Ah ! Got it, thanks. In fact we have a few mappings to KEGG that are no reactions, but pathways. These are all linked to the term 
GO:0052863  1-deoxy-D-xylulose 5-phosphate metabolic process

Mappings are: 
xref: KEGG:ko00730 "Thiamine metabolism"
xref: KEGG:ko00900 "Terpenoid backbone biosynthesis"
xref: KEGG:ko01100 "Metabolic pathways"
xref: KEGG:ko01110 "Biosynthesis of secondary metabolites"
xref: KEGG:map01060 "Biosynthesis of plant secondary metabolites"
xref: KEGG:map01062 "Biosynthesis of terpenoids and steroids"
xref: KEGG:map01066 "Biosynthesis of alkaloids derived from terpenoid and polyketide"
xref: KEGG:map01070 "Biosynthesis of plant hormones"
intersection_of: GO:0008152 ! metabolic process

I propose we delete them. It may be interesting to have cross-refs to KEGG pathways, but this is the only process that has them. We should get these in by our normal process (I'll get in touch with KEGG).

Thanks, Pascale

Pascale

**Comment by pgaudet** [comment] 2019-08-14 09:37
https://github.com/geneontology/go-ontology/pull/17711

**Comment by cmungall** [comment] 2020-02-27 18:08
I wouldn't have removed perfectly good information; in fact we should have made this complete.

We need more joined up thinking here, from the decision to change the prefixes in the ontology to understanding how this looks to users.

I'm not sure the decision to change the xref prefix was a good one. Note that identifiers.org still uses KEGG, e.g. this resolves http://identifiers.org/KEGG:R03084. The simplest and safest thing to do would have been to change our db-xrefs.yaml to match identifiers.org. But here we are...

Note that we have a page on our website for downloading mappings

http://geneontology.org/docs/download-mappings/

This still has the link to kegg2go, which now resolves to a 2 line file

```
! Generated on 2020-02-21T22:21Z from the ontology 'go' with data version: 'releases/2020-02-21'
!
```

This is totally expected behavior but will be hugely confusing to our users.

I'm closing this ticket as everything now has expected behavior, but opening a new ticket to fix website

**Closed by cmungall** 2020-02-27 18:08 UTC
Labels: bug (B: affects usability)

**Comment by pgaudet** [comment] 2020-02-27 18:56
Don't we want to generate the file the the new links ? 

xref: KEGG_REACTION:R05612

1889 instances in the go file. 

Thanks, Pascale

**Comment by cmungall** [comment] 2020-03-02 06:30
Yep, should have been more clear, the file exists:

http://geneontology.org/external2go/kegg_reaction2go

We just need to update the website
