### ISSUE TITLE
Improve parsing for DB:Reference (column 6, gorule-0000055) -- too many publications

### ISSUE THREAD

**Issue by alexsign** [geneontology/go-site#1063] opened 2019-04-23 08:51 UTC
The GAF file gene_association.rgd.gz  downloaded from 
ftp://ftp.geneontology.org/pub/go/gene-associations/
was rejected by GOA pipeline for about a week due to errors in the DB:Reference (column 6)

Here is the example:
MGI:MGI:1329760|MGI:MGI:1337547|MGI:MGI:3709684|MGI:MGI:56958|MGI:MGI:61034|MGI:MGI:73463|PMID:10215924|PMID:2061715|PMID:3783318|PMID:7668363|PMID:7683855|PMID:9918704|RGD:1624291

**Comment by kltm** [comment] 2019-04-23 20:07
@alexsign 
Eyeballing this, I'm not immediately struck by anything that would be erring. Is it the rather expansive list itself? Would you have a reference for the GO Rule it is violating?

@dougli1sqrd @pgaudet Any thoughts on this.

Either way, if there is an RGD issue, it may be worthwhile to bring it up with the upstream as well.

**Comment by kltm** [comment] 2019-04-23 20:12
@alexsign For reference, the RGD upstream we use is https://github.com/rat-genome-database/rgd-annotation-files/raw/master/gene_association.rgd.gz (although the should probably still be synchronizing), as referenced here: https://github.com/geneontology/go-site/blob/master/metadata/datasets/rgd.yaml . The FTP server will be discontinued in the future.
For filtered/processed GAFs, more information is here: http://wiki.geneontology.org/index.php/Release_Pipeline#Types_of_releases

**Comment by cmungall** [comment] 2019-04-23 20:40
The reference column should only denote a single publication; multiple IDs
indicate alternate IDs. I assume Alex is checking to see if there is >1 ID
in the same ID space, which is a sane check we should implement at the
parser level

**Comment by kltm** [comment] 2019-04-23 21:28
@pgaudet @dougli1sqrd Could we start a new rule for this?

**Comment by cmungall** [comment] 2019-04-23 21:55
More generally, we agreed that we would all work on getting all protein2go
rules specified as gorules, do we have a ticket for this?

**Comment by alexsign** [comment] 2019-04-24 09:05
@kltm If you talking about the new GORULE, I'm not sure if it is really needed. One PMID + alternative ID per line for column 6, as Chris posted above,  is clearly stated on GAF specs
 http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/

**Comment by pgaudet** [comment] 2019-04-24 16:29
> More generally, we agreed that we would all work on getting all protein2go rules specified as gorules, do we have a ticket for this?

These are all in the different newly created (but not yet implemented) rules - although this specific one is in gorule0000001 "GAF lines are parsed according to GAF 2.1 specifications" but the specifics of what is checked are not listed. (Seth said it would be too much to describe everything the parser does). 

Should this be a separate rule? 


Thanks, Pascale

**Comment by kltm** [comment] 2019-04-24 18:48
It's fine to have it as 0000001. I've hijacked this ticket to work on the problem at our end.
@pgaudet Somebody should probably contact RGD as we will start dropping these lines soon and they may want to proactively fix them.

**Comment by pgaudet** [comment] 2019-04-25 09:54
@slaulederkind

**Comment by pgaudet** [comment] 2019-04-25 09:54
@kltm Are these in the error reports ?

**Comment by kltm** [comment] 2019-04-25 21:33
Likely not if it's not getting dropped.

**Comment by dougli1sqrd** [comment] 2019-04-29 21:20
I confirmed that in ontobio we are just not checking for more than reference. And looking through the rest of the go rules, I agree, it seems like gorule 1 is the best option. We can fix this in ontobio.

**Comment by cmungall** [comment] 2019-05-08 21:07
I spoke to Eric, this is how we are progressing

 1. We will implement an additional syntactic check (thus subsumed under rule 1) such that warnings are emitted if we see >1 ID per IDSpace in one line. This can only happen if distinct publications are referenced. We cannot repair this one in a systematic way. I think this should be a warn rather than throwing out the annotation, because the annotation may still be biologically valid.
 2. We should refine https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000033.md so that fail_mode=soft, because there is too high a chance of removing valid annotations (e.g. if a group provides a MOD ID but no PMID)

**Comment by dougli1sqrd** [comment] 2019-05-09 21:34
https://github.com/biolink/ontobio/pull/326 for number 1
and
https://github.com/biolink/ontobio/pull/327 for number 2 and gorule 33 implementation.

When these are merged and released, we should see this show up in the pipeline snapshot in a few days.

**Comment by kltm** [comment] 2019-11-19 19:56
This is waiting on a release to merge PRs, and will then be closed.

**Comment by pgaudet** [comment] 2020-08-13 13:46
Where does this stand ? We noticed that the EcoCyc GAF has some lines that have more than on PMID. 

Thanks, Pascale

**Comment by kltm** [comment] 2020-08-19 21:40
@pgaudet Okay, an update:

For 1) above, we have an old PR to address the multiple IDs from the same namespace: https://github.com/biolink/ontobio/pull/326 , but it needs to be updated and folded in. After that is folded in, we can also close https://github.com/geneontology/go-site/issues/1233 .

For 2) above, 0000033 was updated with https://github.com/biolink/ontobio/pull/327 , then deprecated later on in the year (deemed unnecessary).

**Comment by pgaudet** [comment] 2020-08-20 11:57
Can we expect this to be done for the next release (Sept?)

**Comment by kltm** [comment] 2020-08-24 21:25
I think that we're likely to not quite hit it, but it will be close. It may be safer to let this release go and roll it in with other changes for the next month (including some ontobio refactor https://github.com/biolink/ontobio/issues/450).

**Comment by dougli1sqrd** [comment] 2020-09-21 19:43
http://snapshot.geneontology.org/reports/ecocyc-report.html#gorule-0000055

gorule-0000055 seems to be functioning after updating ontobio version.

**Comment by dougli1sqrd** [comment] 2020-09-22 22:20
@pgaudet

**Comment by dougli1sqrd** [comment] 2020-09-30 19:35
@pgaudet For example: http://snapshot.geneontology.org/reports/ecocyc-report.html#gorule-0000055

**Comment by pgaudet** [comment] 2020-09-30 20:12
Looks good, thanks for the example !

**Closed** 2020-10-01 20:19 UTC
Labels: annotation rule, bug (B: affects usability)
