### ISSUE TITLE
"Predictions" not enough information

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#862] opened 2018-10-17 16:12 UTC
I don't know what to do with this information? Is it an error? 

GO:0055114	oxidation-reduction process	AnnotationPropagation	P	GO:0004791	thioredoxin-disulfide reductase activity	IMP
GO:0098869	cellular oxidant detoxification	AnnotationPropagation	P	GO:0004791	thioredoxin-disulfide reductase activity	IMP
GO:0006412	translation	AnnotationPropagation	P	GO:0033417	CUU codon-amino acid adaptor activity	ISM
GO:0006412	translation	AnnotationPropagation	P	GO:0033451	GUA codon-amino acid adaptor activity	ISM
GO:0006412	translation	AnnotationPropagation	P	GO:0033453	GCU codon-amino acid adaptor activity	ISM

**Comment by kltm** [comment] 2021-12-09 08:08
Dupe of more recent https://github.com/geneontology/go-site/issues/1755

**Closed by kltm** 2021-12-09 08:08 UTC
