### ISSUE TITLE
gorule-0000013 incorrectly reports errors

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1245] opened 2019-11-26 10:24 UTC
Hello, 

gorule-0000013 incorrectly reports errors, for example: 

http://snapshot.geneontology.org/reports/goa_human-report.html#gorule-0000013

The first line reporting errors for this rule is : 

    WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- UniProtKB A6NGB9 WIPF3 GO:0000147 PMID:21873635 IBA PANTHER:PTN001506182|PomBase:SPAC4F10.15c|PomBase:SPBC13E7.09 P WAS/WASL-interacting protein family member 3 WIPF3|CR16 protein taxon:9606 20170228 GO_Central

But there is no taxon constraint on GO:0000147. 

Thanks, Pascale

**Comment by kltm** [comment] 2019-11-26 19:20
@balhoff It looks like @pgaudet does not think the output is correct.

**Comment by kltm** [comment] 2019-11-26 19:24
@dougli1sqrd Could you add suppression for this rule until it has been fixed upstream.

**Comment by balhoff** [comment] 2019-11-26 21:06
@pgaudet this comes from `'actin cortical patch' 'only in taxon' 'Fungi'`, which is in GO.

**Comment by kltm** [comment] 2019-11-26 21:33
@dougli1sqrd I guess hold off as this seems to be expected.

**Comment by vanaukenk** [comment] 2019-11-26 22:17
Are we also be getting taxon violations based on logical defs that use terms from external ontologies?

The WB file had annotations to GO:0043282 'pharyngeal muscle development' flagged for taxon violations, I _think_ based on the use of UBERON:0000933 'pharyngeal muscle' in the logical def.

Although the placement of 'pharyngeal muscle development' in GO seems broad enough to include nematodes, 'pharyngeal muscle' in UBERON looks to _part of_ 'musculoskeletal system' which wouldn't apply to nematodes and there is no mapping between the WBbt and UBERON terms in the bridge file.

I can move this particular discussion to the go-ontology tracker but wanted to check here to see if the reason for the flag is correct before I do.

Thx.

**Comment by pgaudet** [comment] 2019-11-27 09:57
Interesting. 

We don't use the relation 'occurs in' to predict taxon constraints but we do use 'results in assembly of' - so there *are* taxon constraints that go across CC -> BP. That's good to know. 

My source of information for which terms have taxon constraints is QuickGO - but this one is not shown @alexsign 

@balhoff : 
1. could we show 'inferred' taxon constraints in Protégé ? 
2. Could you export a list of all taxon constraints (direct and inferred ) 
3. Do we have the list of rules for inferences of taxon constraints ? This should be documented (ie which relations are being used).

Thanks, Pascale

**Comment by balhoff** [comment] 2019-11-27 15:53
> could we show 'inferred' taxon constraints in Protégé ?

We have [some documentation](http://wiki.geneontology.org/index.php/Adding_Taxon_Restrictions#Checking_existing_taxon_constraints) on how to check for a particular constraint. To show them all conveniently requires exhaustive queries, which we do to generate the table (below).

> Could you export a list of all taxon constraints (direct and inferred )

We have functionality in gaferencer to output this. Originally this was intended to be used in the panther pipeline. @dustine32 @dougli1sqrd is this table produced and stored anywhere right now?

> Do we have the list of rules for inferences of taxon constraints ? This should be documented (ie which relations are being used).

This is in RO. It's the property chains for [in taxon](http://www.ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002162).

**Comment by pgaudet** [comment] 2019-11-27 16:09
It would be useful to have access to that table. 

Another query: in the report, would it be difficult to output the actual taxon constraint violated in the message 
    WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- UniProtKB A6NGB9 WIPF3 GO:0000147 PMID:21873635 IBA PANTHER:PTN001506182|PomBase:SPAC4F10.15c|PomBase:SPBC13E7.09 P WAS/WASL-interacting protein family member 3 WIPF3|CR16 protein taxon:9606 20170228 GO_Central

Add 'only in fungus' somewhere ? 

Thanks, Pascale

**Comment by vanaukenk** [comment] 2019-11-27 16:56
Thanks @balhoff 
The property chains account for the taxon restriction that flagged the WB 'pharyngeal muscle development' annotations.
I think this then becomes an ontology issue, so I'll create a ticket in the ontology tracker.

**Comment by dougli1sqrd** [comment] 2019-11-27 19:03
@pgaudet I don't have any information at the time of the reporting about *why* the taxon checks failed. 

@balhoff we only operate in "GAF" mode for gaferencer, we don't produce the table that Dustin uses.

**Comment by pgaudet** [comment] 2019-11-28 08:33
> I don't have any information at the time of the reporting about why the taxon checks failed.

Is this something that can be obtained anywhere ? Because for ontology editors we can do the DL query, but most curators do not use Protegé while curating, so they rely on error messages. 

Thanks, Pascale

**Comment by dustine32** [comment] 2019-12-06 18:03
> @dustine32 @dougli1sqrd is this table produced and stored anywhere right now?

@balhoff I currently run `gaferencer taxa` and do some transformations to make it more PAINT-digestable. Specifically adding in the PANTHER ancestor species (e.g. Metazoa-Choanoflagellida) and converting taxonID to the RefProt 5-letter codes (e.g. NCBITaxon:39947 -> ORYSJ).

This transformed taxon-term table file is then uploaded to our FTP server here:
http://data.pantherdb.org/TaxonConstraints/TaxonConstraintsLookup.txt

**Comment by cmungall** [comment] 2019-12-10 23:49
what is the action here? AFAICT there is no error so we can close this?

**Closed** 2019-12-11 09:38 UTC
Labels: annotation rule, bug (B: affects usability)
