### ISSUE TITLE
gorule-0000030 - Needs to be a warning

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1420] opened 2020-03-16 19:38 UTC
There are too many annotations that fails. Can you change this ? We need this for the next release to go out. 

Thanks, Pascale

**Comment by kltm** [comment] 2020-03-16 20:15
@pgaudet I'm trying to understand the status change here. Is there a bug in 0000030? We've had that as it is now for well over a year and only threee species seem to be having trouble. Is there a reason for the sudden change?

**Comment by pgaudet** [comment] 2020-03-16 22:00
Yes, I have been cleaning up redundant gorefs and some groups annotations
to now obsoleted gorefs.

We should keep it a warning until the gorefs are completely cleaned up.

BTW it would be useful if the Readme. MD page was updated.

Thanks, Pascale

**Comment by kltm** [comment] 2020-03-16 22:15
@pgaudet 
"We should keep it a warning until the gorefs are completely cleaned up."
Could you make a ticket for the re-reversion then? We can reference that when we close out this one.

**Comment by kltm** [comment] 2020-03-16 22:16
@pgaudet That said, is switching to "warning" (and letting thousands more annotations in) actually blocking a `release` run for you?

**Comment by pgaudet** [comment] 2020-03-17 07:59
Yes @kltm this is OK. 
In the current release, this rule has no errors. We are not introducing any errors in the data, we just want people to switch to a different reference number. 

Thanks for confirming, 

Pascale

**Comment by kltm** [comment] 2020-03-17 17:51
@pgaudet Apologies, I'm still unclear with the response in https://github.com/geneontology/go-site/issues/1420#issuecomment-599929378. Is turning this rule to a warning actually blocking requesting a `release` run for you?

- [ ] yes
- [ ] no

As well, could you make a ticket for the re-reversion (switching this rule back to an "error" from a "warning")?

**Comment by pgaudet** [comment] 2020-03-17 17:57
This is why I put 'blocker' as the label. 

Thanks, Pascale

**Comment by dougli1sqrd** [comment] 2020-03-17 23:16
Okay, let's check back in the next snapshot build. I've updated ontobio with the new gorule-0000030 implementation along with changing the rule document in go-site. Ontobio is released and the new version with the change is set in go-site.

**Comment by kltm** [comment] 2020-03-23 18:13
@dougli1sqrd Has this been cleared?

**Comment by dougli1sqrd** [comment] 2020-03-23 18:20
It looks like it. I believe we can close this issue.

**Comment by kltm** [comment] 2020-03-23 18:23
I can confirm that gorule-0000030 appears as a warning in the last `snapshot` report.

**Closed by kltm** 2020-03-23 18:23 UTC
Labels: bug (A: showstopper)
