### ISSUE TITLE
Update trees to panther10

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#187] opened 2016-05-24 03:02 UTC
- [ ] do a test slurp of http://pantherdata.usc.edu/PANTHER10.0/ using wget (note: should be no need to run paint scraper any more). Looks like this is the job: https://build.berkeleybop.org/job/panther-update
- [ ] rename files to follow the naming conventions we use (e.g. PTHRnnnn.tree, not tree.tree)
- [ ] test conversion to json
- [ ] switch to default

**Comment by selewis** [comment] 2016-05-24 03:19
Scraper hasn't been used for the past two releases. The wget command line
is in GitHub.

**Comment by kltm** [comment] 2016-05-24 05:09
To pull it all the way through to AmiGO, there were a few more steps. Poking around, I found one of the file fixers that was used on the last set: svn/geneontology.org/trunk/experimental/trees/fix-panther.pl. That seems to run the clean-up in place where the data lives.

**Comment by cmungall** [comment] 2016-05-24 12:57
@selewis - when you say the wget is in github, which repo do you mean? Note our jenkins job has the complex wget command directly in the conf, i.e not under version control.

@kltm - I see the fix-panther script. Looks like it does some escaping on the arbre files.

I think we just need to wrap this all in a single script, combine it with validation (presumably using the same code we load into either touchup or the golr loader or both)

**Comment by selewis** [comment] 2016-05-24 19:42
@cmungall It's here:
https://github.com/geneontology/panther-release-wrangling in the read me.
The commits was done manually.

@ktlm - Not sure what script you're talking about. See the above link.
(does need to be wrapped though)

**Comment by kltm** [comment] 2016-05-24 20:32
@selewis The script I'm talking about is here https://github.com/geneontology/go-site/issues/187#issuecomment-221167918
It is different from yours import, but it is necessary to clean the trees, etc., before they can be used by owltools during the GOlr load process.

**Comment by selewis** [comment] 2016-05-24 21:17
It's coming back to me now. We sketched out the series of steps required
for import in the readme.  touchup can use the raw files directly, but
there were some additional steps.  I hope we don't have 2 different wget-s!

**Comment by kltm** [comment] 2018-08-22 21:32
Now dupe of 
https://github.com/geneontology/amigo/issues/532

**Closed by kltm** 2018-08-22 21:32 UTC
