### ISSUE TITLE
Create rules for use of PR in c17 of GAF

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#186] opened 2016-05-17 20:30 UTC
The ecocyc GAF has lines such as this:

```
UniProtKB P0AD01 dcuR GO:0006355 GO_REF:0000037 IEA SP_KW:KW-0805 P DcuR transcriptional activator dcuR|yjdG|b4124|ECK4117 protein taxon:83333 20140118 UniProtKB PR:000022415
```

Note here the c17 value is actually the superclass of the protein in c2:
http://www.proconsortium.org/cgi-bin/pro/entry_pro?id=PR:000022415

This should be invalid. c17 is for indicating a specific isoform of the generic organism-gene level entry in c2. It isn't an ID mapping column.

I propose a new annotation rule:

If a PR ID is used in c17, it must be Category=organism-gene or below (even Category=organism-gene is debatable, as this is the same level of specificity as what is in c2).

https://www.ebi.ac.uk/panda/jira/browse/GO-278

**Comment by dougli1sqrd** [comment] 2019-11-26 20:56
Duplicate of https://github.com/geneontology/go-site/issues/835

**Closed by dougli1sqrd** 2019-11-26 20:56 UTC
Labels: annotation rule, duplicate
