### ISSUE TITLE
user stories

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#144] opened 2016-01-12 14:44 UTC
http://geneontology.org/page/user-stories

The User Story Story
User stories represent a way of looking at the information that the Gene Ontology offers.

When clicking on this I expect something like http://www.ebi.ac.uk/about/jobs/career-profiles/scientific-curator - perhaps we should change the heading?

**Comment by kltm** [comment] 2016-04-20 20:56
Dupe of #177.

**Closed by kltm** 2016-04-20 20:56 UTC
Labels: docs-ontology
