### ISSUE TITLE
Migrate http contributor orcid ids in go-cam models to correct https version

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1907] opened 2022-09-23 01:15 UTC
During the [2022-09-22 Noctua maintenance outage](https://github.com/geneontology/noctua/issues/790), we noticed that there are a number of http orcid identifiers still lurking in models.  

These need to be migrated to their https version, if that version is not already associated with the model.

Some examples include:

http://noctua.geneontology.org/editor/graph/gomodel:SYNGO_993

http://noctua.geneontology.org/editor/graph/gomodel:MGI_MGI_3031090

We may also want to double-check that all contributors are in the users.yaml file while we're at it.

**Comment by kltm** [comment] 2022-09-23 19:22
Found the last time we ran into this, about a year ago: https://github.com/geneontology/noctua-models/issues/194

**Comment by kltm** [comment] 2022-09-23 19:53
@vanaukenk So, the metadata seems to be clean and we did a cleaning update a year ago, which means that these got in during an import (or imports) or there is a systematic issue.
```
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:) grep --no-file --only-matching "http\:\/\/orcid.org\/[0-9a-zA-Z\-]*" *.ttl | sort | uniq
```
http://orcid.org/0000-0001-5259-4945
http://orcid.org/0000-0001-5501-853X
http://orcid.org/0000-0001-5518-6584
http://orcid.org/0000-0001-7351-8706
http://orcid.org/0000-0001-7476-6306
http://orcid.org/0000-0001-7806-5662
http://orcid.org/0000-0001-9377-7414
http://orcid.org/0000-0001-9425-2935
http://orcid.org/0000-0001-9783-5183
http://orcid.org/0000-0001-9990-8331
http://orcid.org/0000-0002-0269-0311
http://orcid.org/0000-0002-0755-5899
http://orcid.org/0000-0002-0808-7003
http://orcid.org/0000-0002-1190-4481
http://orcid.org/0000-0002-1212-5623
http://orcid.org/0000-0002-1558-1958
http://orcid.org/0000-0002-1585-539X
http://orcid.org/0000-0002-2094-7491
http://orcid.org/0000-0002-2286-1587
http://orcid.org/0000-0002-2345-393X
http://orcid.org/0000-0002-2514-0216
http://orcid.org/0000-0002-2666-0758
http://orcid.org/0000-0002-3670-7863
http://orcid.org/0000-0002-3898-5197
http://orcid.org/0000-0002-4419-210X
http://orcid.org/0000-0002-4973-5732
http://orcid.org/0000-0002-5265-6306
http://orcid.org/0000-0002-5615-1014
http://orcid.org/0000-0002-5676-366X
http://orcid.org/0000-0002-6153-3586
http://orcid.org/0000-0002-7620-2704
http://orcid.org/0000-0002-9681-3318
http://orcid.org/0000-0002-9796-7693
http://orcid.org/0000-0002-9848-0262
http://orcid.org/0000-0002-9880-1214
http://orcid.org/0000-0002-9888-0928
http://orcid.org/0000-0002-9900-4233
http://orcid.org/0000-0003-0575-6950
http://orcid.org/0000-0003-0593-3443
http://orcid.org/0000-0003-0662-9523
http://orcid.org/0000-0003-0912-1514
http://orcid.org/0000-0003-0938-8534
http://orcid.org/0000-0003-1542-3498
http://orcid.org/0000-0003-2533-9548
http://orcid.org/0000-0003-2689-5511
http://orcid.org/0000-0003-2916-7616
http://orcid.org/0000-0003-2949-9725
http://orcid.org/0000-0003-3185-5709

Also, worryingly, apparently ORCIDs can be "deactivated" (see http://orcid.org/0000-0002-2514-0216)? Not ideal for something that is supposed to be a URI...
I'm going to continue tracing through.

**Comment by ukemi** [comment] 2022-09-23 19:57
I suspect the import theory is correct since the two cited sources are both the result of imports.

**Comment by kltm** [comment] 2022-09-23 20:20
Helpfully, we track our imports through GH now, so we can go systematically:

- reactome-go-cams: clean
- yeast-pathways-go-cams: clean
- mgi-go-cams
http://orcid.org/0000-0001-5501-853X
http://orcid.org/0000-0001-7476-6306
http://orcid.org/0000-0001-9990-8331
http://orcid.org/0000-0002-9796-7693
http://orcid.org/0000-0003-2689-5511
- wb-go-cams: clean
- zfin-go-cams: clean
- syngo-go-cams: 
_loooots_

So, yeah, I think we're going to probably mostly chalk this up to import.
MGI is already imported, so fixing in the noctua-models repo should be sufficient. I would still recommend getting these updated in the source in case somebody looks at them though. For syngo, I think we should do a fix and a re-import.

@dustine32 @vanaukenk we have a while before the next cycle. I'm assuming that we'd wait until then as it's a handful of MGI ids and syngo, which does not get edited. We could go earlier though. Talk about next week on software?

**Comment by kltm** [comment] 2022-09-23 20:21
@dustine32 Also, do you think this is stale metadata use, or something in the tooling?

**Comment by vanaukenk** [comment] 2022-09-23 20:26
@kltm I'm okay with updating these on the next maintenance cycle, unless SynGO gets in touch with us about not being able to search their models by contributor.  @ukemi do you think this is okay for MGI?

I'm a little puzzled why we didn't catch this previously, or is it possible it's a new bug?

**Comment by kltm** [comment] 2022-09-23 20:31
@vanaukenk Given the distribution, which seems to be SynGO and MGI (although not 100% confirmed), I don't think it's a general "live" bug, but only two specific imports via cold files.
As for why we didn't see it earlier...I have no idea. Personally, I'd love to get some QC onto the noctua-models repo to try and get ahead of things like this.

**Comment by ukemi** [comment] 2022-09-23 20:37
I am wrote a ticket for MGI. I don't think it will be an issue, but as usual I will defer to @loricorbani. But as @kltm says, this is a one time import and even if we fix it at MGI, someone needs to fix it on the GOC side.

**Comment by kltm** [comment] 2022-09-23 20:40
Setup for fixing during. https://github.com/geneontology/noctua/issues/792
Heading towards the 13th, we'll want to:
- [ ] update mgi-go-cams (for cleanliness)
- [ ] update syngo-go-cams (for re-import)
- [ ] double check reason for http; metadata or tooling

**Comment by dustine32** [comment] 2022-09-23 20:56
@kltm For MGI, the `ontobio/gocamgen` code should just be pulling whatever `contributor-id` annotation properties values are on the input GPAD (`go_cam_mgi.gpad`). In the example GO-CAM I see two http and https contributor annotations for the same ORCID:
![image](https://user-images.githubusercontent.com/2678599/192054349-0c980a41-0dfc-4939-bf10-50e3d9f7aa5f.png)
Maybe the bulk update in minerva was an append instead of a replace? Regardless, you think we can just do a `sed` replace on the `noctua-models/master` MGI models and `mgi-go-cams` separately? Or should we follow the "update `mgi-go-cams` -> PR to `noctua-models/master`" method? I'd assume the latter would wipeout any curator changes since the import.

For SynGO, we can redo the full load and I'm leaning on updating the http ORCIDs in the input JSON here: [SynGO_export_2021-02-25.json](https://github.com/geneontology/syngo2lego_data_conversion/blob/master/json/SynGO_export_2021-02-25.json)

**Comment by dustine32** [comment] 2022-09-23 20:57
@kltm Also, I'm out next Thurs & Fri so maybe we can talk early next week?

**Comment by kltm** [comment] 2022-09-23 21:16
@dustine32 Okay, it sounds like upstream issues then, which is good.
I think we want to cleanup the data in the repos either way. As far what fixes we should run, I've tried to clear up https://github.com/geneontology/go-site/issues/1907#issuecomment-1256651758; let me know if the procedure is unclear or we can chat about it on some channel.

**Comment by dustine32** [comment] 2022-09-28 01:55
Confirmed those ORCID "dupes" (both http and https for same ORCID) are directly from the upstream `go_cam_mgi.gpad` file. I see this example line in the prod load [source GPAD](https://github.com/geneontology/mgi-go-cams/blob/mgi-imports-20220328/source/go_cam_mgi.gpad):
```
MGI:MGI:3031090         RO:0002264      GO:0007186      MGI:MGI:3029684|PMID:14611657   ECO:0000247     UniProtKB:Q9QW37                2005-09-26      MGI             creation-date=2004-10-13|modification-date=2005-09-26|comment=homol_start_in_CDS=1 homol_end_in_CDS=900 homol_start_in_pep=1 homol_end_in_pep=300 percent_ident(pep)=66.667|contributor-id=GOC:bobs|contributor-id=http://orcid.org/0000-0001-7476-6306|contributor-id=https://orcid.org/0000-0001-7476-6306
```
Containing annotation properties:
```
contributor-id=http://orcid.org/0000-0001-7476-6306|contributor-id=https://orcid.org/0000-0001-7476-6306
```
I ran @kltm's `find` and `sed` cmd and [merged](https://github.com/geneontology/mgi-go-cams/pull/15) these into the mgi-go-cams repo.

**Comment by kltm** [comment] 2022-09-28 19:55
Cheers @dustine32 ! Just to reinforce this for future reader: the MGI models are _not_ going to be re-merged with noctua-models `master`, but rather we'll do a bulk update at the next outage (after we do a re-import of the fixed _Reactome_).

**Comment by dustine32** [comment] 2022-09-28 23:21
Marking that I have the `syngo-go-cams` repo updated with https://github.com/geneontology/syngo-go-cams/pull/5 and a [PR](https://github.com/geneontology/noctua-models/pull/244) for these SynGO models to go into `noctua-models/master` whenever needed.

**Comment by kltm** [comment] 2022-10-13 23:16
All tasks completed.

**Closed by kltm** 2022-10-13 23:16 UTC
Labels: bug (B: affects usability), metadata
