### ISSUE TITLE
gorule-0000013 taxon constraints: Filter non EXP, Report for EXP annotations

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#882] opened 2018-11-06 17:15 UTC
(edited, IEA was missing) 
Taxon constraints
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000013.md

Should this first be implemented as a report, and later as a filter? 

gorule-0000013 should filter non experimental annotations that violate taxon constraints: **IEA**, IBA, IKR, IRD, IC, ISA, ISM, ISO, ISS, NAS, RCA, TAS , ND. Other evidence code annotations should not be filtered.

Additionally, negated annotations with `NOT` in the qualifier field in GAF/GPAD should not have taxon constraints applied to them.

**Comment by pgaudet** [comment] 2020-01-08 20:09
This was discussed at today's PI call. We decided that 
- EXP would be warnings
- non EXP annotations would be filters. 
@dougli1sqrd does this need to be a new rule ? Or can I edit gorule-0000013 ? 

Thanks, Pascale

**Comment by pgaudet** [comment] 2020-01-15 17:57
Another request for gorule-0000013: taxon constraints DO NOT apply to NOT annotations, see https://github.com/geneontology/go-site/issues/1256


Thanks, Pascale

**Comment by dougli1sqrd** [comment] 2020-04-01 19:28
@pgaudet I believe this can be closed?

**Comment by pgaudet** [comment] 2020-04-02 14:50
No - IEAs and IBAs failing the checked should be filtered, we still only have a WARNING (see comment above: https://github.com/geneontology/go-site/issues/882#issuecomment-572235971). 

See for example the first gorule-0000013 error in http://skyhook.berkeleybop.org/release/reports/aspgd-report.html#gorule-0000013

WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- AspGD ASPL0000059928 AN0127 GO:0032258 AspGD_REF:ASPL0000000005 **IEA** SGD:S000001917 P AN0127|ANID_00127|ANIA_00127 gene_product taxon:227321 20200201 AspGD

---

I am also surprised not to find any IBAs violating the rule. 

Thanks, Pascale

**Comment by dougli1sqrd** [comment] 2020-04-02 16:45
Thanks Pascale. I'm looking into this.

**Comment by pgaudet** [comment] 2020-04-02 18:40
OK - also can you check why there are no IBAs being reported ? we have thousands of errors.

**Comment by cmungall** [comment] 2020-04-02 19:02
> I am also surprised not to find any IBAs violating the rule

let's look into this - any ideas where to start?

**Comment by dougli1sqrd** [comment] 2020-04-02 19:13
I just checked with @pgaudet and she was expecting IBA taxon errors to appear in non-paint files. But we remove all IBA lines in non-paint files, so we will never see taxon errors for IBA in those files (fb, goa_human, etc). Only IBA taxon errors will appear in paint files. 

That seemed to make sense to her after we chatted though. @pgaudet did I miss anything?

**Comment by dougli1sqrd** [comment] 2020-04-07 00:40
Looks like http://snapshot.geneontology.org/reports/aspgd-report.html#gorule-0000013 that these lines are properly being filtered now. @pgaudet does this fix this issue?

**Comment by pgaudet** [comment] 2020-05-17 10:23
@dougli1sqrd 
I can still see IBA annotations that fail the taxon constraints and that are displayed in AmiGO, for eg SGD 

ERROR - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- SGD S000006055 ODC1 GO:0015813 PMID:21873635 IBA PANTHER:PTN000640304|UniProtKB:O75746|UniProtKB:Q9H936|FB:FBgn0260743|MGI:MGI:1354721|FB:FBgn0037970|SGD:S000006225|UniProtKB:Q9UJS0 P Mitochondrial 2-oxodicarboxylate carrier 1 UniProtKB:Q03028|PTN000640830 protein taxon:559292 20170228 GO_Central


Can you please check ? 

@kltm

**Comment by dougli1sqrd** [comment] 2020-05-18 19:44
Can you link to where you see the annotation in amigo, Pascale? Thanks

**Comment by kltm** [comment] 2020-05-18 21:30
@pgaudet @dougli1sqrd This is likely the annotation (noting the label "upgrade" from SGD pseudo-GPI):
http://amigo-exp.geneontology.io/amigo/search/annotation?q=ODC1*&fq=taxon_subset_closure_label:%22Saccharomyces%20cerevisiae%20S288C%22&fq=evidence_subset_closure_label:%22similarity%20evidence%20used%20in%20manual%20assertion%22&fq=annotation_class_label:%22L-glutamate%20transmembrane%20transport%22&sfq=document_category:%22annotation%22

**Comment by dougli1sqrd** [comment] 2020-05-19 20:53
Okay the plot thickens.

The `paint_sgd_valid` in products/annotations has the offending annotation.
The `paint_sgd.gaf.gz` in poducts/annotations *does not* have the offending annotation.

```
(env) dougli1sqrd@neighbor:~/lbl/geneontology/go-site/pipeline(master) $ curl -L http://snapshot.geneontology.org/products/annotations/paint_sgd_valid.gaf.gz | gzip -dcf | grep ODC1 | grep 0015813
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1221k  100 1221k    0     0  2120k      0 --:--:-- --:--:-- --:--:-- 2117k
SGD	S000006055	ODC1		GO:0015813	PMID:21873635	IBA	FB:FBgn0037970|FB:FBgn0260743|MGI:MGI:1354721|PANTHER:PTN000640304|SGD:S000006225|UniProtKB:O75746|UniProtKB:Q9H936|UniProtKB:Q9UJS0	P	Mitochondrial inner membrane transporter	YPL134C|mitochondrial 2-oxodicarboxylate carrier	protein	taxon:559292	20170228	GO_Central		
(env) dougli1sqrd@neighbor:~/lbl/geneontology/go-site/pipeline(master) $ curl -L http://snapshot.geneontology.org/products/annotations/paint_sgd.gaf.gz | gzip -dcf | grep ODC1 | grep 0015813
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1058k  100 1058k    0     0  12.7M      0 --:--:-- --:--:-- --:--:-- 12.7M
(env) dougli1sqrd@neighbor:~/lbl/geneontology/go-site/pipeline(master) $ 

```

**Comment by dougli1sqrd** [comment] 2020-05-19 21:09
Okay I'm pretty sure I know what's happening. 

This is the "multiple pass" problem showing up again. 

In ontobio, when we're processing sgd, we use sgd gaference results to do taxon checks. Then when we are mixing in paint_sgd, we re-download, re-process paint_sgd, but we don't have the paint_sgd gaferences, additionally since we're not strictly speaking making reports on the mixins (those reports when processing the mixins as actual products) we don't do the full rule processing.

So in paint_sgd this is properly being reported and filtered, but then when we make sgd, the offending annotation gets merged in because of the multi-pass approach.

**Comment by kltm** [comment] 2020-06-08 18:05
@dougli1sqrd Is this a functional dupe of #1484 ?

**Comment by kltm** [comment] 2020-06-09 00:07
@pgaudet I believe that the "original" item is cleared, but that https://github.com/geneontology/go-site/issues/882#issuecomment-629774929 essentially started a new item, which is #1484 .

**Comment by pgaudet** [comment] 2020-06-09 13:52
So we can close this ticket?

**Comment by kltm** [comment] 2020-06-09 17:58
That has my vote!

**Closed by kltm** 2020-06-09 17:58 UTC
Labels: annotation rule
