### ISSUE TITLE
Clarifying "User stories".

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#180] opened 2016-04-20 15:56 UTC
From Alex Bateman: 
Please clarify what “User stories” are. Perhaps change the name so users can better understand the material contained in these sections.

**Comment by kltm** [comment] 2016-04-20 20:56
Dupe of #177.

**Closed by kltm** 2016-04-20 20:56 UTC
Labels: enhancement

**Comment by monicacecilia** [comment] 2016-04-21 09:20
10-4
