### ISSUE TITLE
GORULE:??? Check for contradictory ND annotation at the top when there actually are annotations for a gp

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#755] opened 2018-08-08 18:21 UTC
_From @selewis on August 8, 2018 17:47_

See "Automatic deletion of ND-evidenced annotations" 
https://github.com/geneontology/go-annotation/issues/2045 

Should be impossible to say that a GP has annotations, but at the same time say there is No Data.

Raise an alert, and exclude the ND annotation

_Copied from original issue: geneontology/pipeline#52_

**Comment by pgaudet** [comment] 2018-09-06 16:55
Duplicate of https://github.com/geneontology/go-site/issues/775

**Closed by pgaudet** 2018-09-06 16:55 UTC
Labels: bug
