### ISSUE TITLE
Travis timing out again

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#760] opened 2018-08-10 13:28 UTC
Also, AmiGO isn't accessible. 

Thanks

**Comment by kltm** [comment] 2018-08-10 14:34
@pgaudet An AmiGO ticket needs to go in the amigo tracker--these are not related, ticket location means it's seen by different people, and will not be solved in the same repo.

**Comment by kltm** [comment] 2018-08-10 14:34
@pgaudet Which Travis checks are timing out?--these are repo-specific.

**Comment by pgaudet** [comment] 2018-08-10 14:51
Hi sorry

The ontology checks. I should have put this in the ontology repo.

Thanks, Pascale

**Comment by kltm** [comment] 2018-08-10 20:19
dupe of #16232

**Closed by kltm** 2018-08-10 20:19 UTC
